### ISSUE TITLE
Docker compose running as specific user and access from non local network

### ISSUE THREAD

**Issue by ma-karai** [Dusk-Labs/dim#294]
Just a quick note:

It would be great to provide a reasonable docker compose file, many selfhoster and homelaber use linuxserver.io images because of the simple settings defined in ENV variables such as defining PGID and PUID this helps with mounting NFS and easy incorporating it into existing setups. Further it should be possible to white list networks that are allowd to access the server, i am sure i am not the only one to have multiple subnets :) Other wise awesome stuff

e.g.:

```
 dim:
   image: vgarleanu/dim:latest
   container_name: dim
   hostname: dim
   environment:
    - PUID=1101
    - PGID=1101
    - TZ=Europe/Berlin
    - GIDLIST=44,109
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
   volumes:
     - /home/docker/dim:/opt/dim/config
     - /mnt/multimedia01:/data/mm
     - /mnt/multimedia02:/data/mm2
   devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
   ports:
     - 8000:8000
   restart: unless-stopped 
```
